In [21]:
!pip install lightgbm

In [22]:
from sklearn import datasets
import numpy as np
import lightgbm as lgb

from scipy.stats import spearmanr

In [23]:
x_train, y_train = datasets.load_svmlight_file("mq2008.train")
x_valid, y_valid = datasets.load_svmlight_file("mq2008.vali")
x_test, y_test = datasets.load_svmlight_file("mq2008.test")

In [24]:
x_train

<9630x46 sparse matrix of type '<class 'numpy.float64'>'
	with 233775 stored elements in Compressed Sparse Row format>

In [25]:
y_train

array([0., 0., 0., ..., 0., 0., 0.])

In [26]:
np.loadtxt('mq2008.train.group')

array([  8.,   8.,   8.,   8.,   8.,  16.,   8., 118.,  16.,   8.,   8.,
         8.,   7.,   8.,  16.,   8.,  16.,   8.,  32.,   8.,   8.,   8.,
        31.,   8.,   8.,  15.,   8.,  15.,   8.,  28.,   7.,  62.,   8.,
         8.,  16.,  16.,   8.,   8.,  15.,   8., 118.,   8.,  16.,   8.,
         8.,  16.,  16.,   8.,  16.,   8.,   8.,   8.,   8.,   8.,  16.,
         8.,  30.,   8.,   8.,   8.,   8.,   8.,  28.,   8., 113.,   7.,
        15.,  25.,   8.,  16.,   8.,  16.,  59.,   8.,   7.,   8.,  31.,
        30.,  31.,  32.,   8.,   8.,  16.,   8.,  31.,  15.,  15.,  28.,
        32.,   8.,  31.,  59.,   8.,   7.,  55.,   8.,   8.,   8.,  32.,
         7.,   8.,  16.,  58.,   8.,  15.,  29.,   8.,  31.,   8.,   8.,
        16.,   8.,   8.,   6.,   8.,  62.,   8.,   8.,  60.,   8.,   8.,
         8.,   8.,   8.,   8.,   7.,   8.,  16.,  13.,   8.,   7.,   8.,
         8.,   8.,   8., 114.,  15.,  31.,   8.,   7.,   8.,   8.,  29.,
         7.,  25.,   8.,   8.,   8., 118.,   7.,   

In [27]:
q_train = np.loadtxt('mq2008.train.group')
q_valid = np.loadtxt('mq2008.vali.group')
q_test = np.loadtxt('mq2008.test.group')

In [28]:
q_train

array([  8.,   8.,   8.,   8.,   8.,  16.,   8., 118.,  16.,   8.,   8.,
         8.,   7.,   8.,  16.,   8.,  16.,   8.,  32.,   8.,   8.,   8.,
        31.,   8.,   8.,  15.,   8.,  15.,   8.,  28.,   7.,  62.,   8.,
         8.,  16.,  16.,   8.,   8.,  15.,   8., 118.,   8.,  16.,   8.,
         8.,  16.,  16.,   8.,  16.,   8.,   8.,   8.,   8.,   8.,  16.,
         8.,  30.,   8.,   8.,   8.,   8.,   8.,  28.,   8., 113.,   7.,
        15.,  25.,   8.,  16.,   8.,  16.,  59.,   8.,   7.,   8.,  31.,
        30.,  31.,  32.,   8.,   8.,  16.,   8.,  31.,  15.,  15.,  28.,
        32.,   8.,  31.,  59.,   8.,   7.,  55.,   8.,   8.,   8.,  32.,
         7.,   8.,  16.,  58.,   8.,  15.,  29.,   8.,  31.,   8.,   8.,
        16.,   8.,   8.,   6.,   8.,  62.,   8.,   8.,  60.,   8.,   8.,
         8.,   8.,   8.,   8.,   7.,   8.,  16.,  13.,   8.,   7.,   8.,
         8.,   8.,   8., 114.,  15.,  31.,   8.,   7.,   8.,   8.,  29.,
         7.,  25.,   8.,   8.,   8., 118.,   7.,   

In [29]:
sum(q_train)

9630.0

In [30]:
x_train.shape

(9630, 46)

In [31]:
gbm = lgb.LGBMRanker()
gbm.fit(x_train, y_train, group=q_train, eval_set=[(x_valid, y_valid)],
eval_group=[q_valid], eval_at=[1, 3], early_stopping_rounds=20, verbose=True,
callbacks=[lgb.reset_parameter(learning_rate=lambda x: 0.95 ** x * 0.1)])

[1]	valid_0's ndcg@1: 0.545648	valid_0's ndcg@3: 0.646204
Training until validation scores don't improve for 20 rounds
[2]	valid_0's ndcg@1: 0.641189	valid_0's ndcg@3: 0.67377
[3]	valid_0's ndcg@1: 0.632696	valid_0's ndcg@3: 0.686982
[4]	valid_0's ndcg@1: 0.630573	valid_0's ndcg@3: 0.682209
[5]	valid_0's ndcg@1: 0.63482	valid_0's ndcg@3: 0.691415
[6]	valid_0's ndcg@1: 0.639066	valid_0's ndcg@3: 0.691675
[7]	valid_0's ndcg@1: 0.639066	valid_0's ndcg@3: 0.689515
[8]	valid_0's ndcg@1: 0.632696	valid_0's ndcg@3: 0.687713
[9]	valid_0's ndcg@1: 0.624204	valid_0's ndcg@3: 0.679523
[10]	valid_0's ndcg@1: 0.590234	valid_0's ndcg@3: 0.672552
[11]	valid_0's ndcg@1: 0.573248	valid_0's ndcg@3: 0.668197
[12]	valid_0's ndcg@1: 0.592357	valid_0's ndcg@3: 0.671442
[13]	valid_0's ndcg@1: 0.590234	valid_0's ndcg@3: 0.670107
[14]	valid_0's ndcg@1: 0.600849	valid_0's ndcg@3: 0.671026
[15]	valid_0's ndcg@1: 0.602972	valid_0's ndcg@3: 0.673608
[16]	valid_0's ndcg@1: 0.590234	valid_0's ndcg@3: 0.671269
[17]	v

LGBMRanker(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
           importance_type='split', learning_rate=0.1, max_depth=-1,
           min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
           n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
           random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
           subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [32]:
preds_train = gbm.predict(x_train)
preds_train

array([ 0.14631787, -0.32150721, -0.00793422, ..., -0.24539755,
       -0.28354248, -0.28354248])

In [33]:
spearmanr(y_train, preds_train)

SpearmanrResult(correlation=0.3843555632065391, pvalue=0.0)

In [34]:
q_train = [x_train.shape[0]]
q_valid = [x_valid.shape[0]]
q_test = [x_test.shape[0]]

gbm = lgb.LGBMRanker()
gbm.fit(x_train, y_train, group=q_train, eval_set=[(x_valid, y_valid)],
eval_group=[q_valid], eval_at=[1, 3], early_stopping_rounds=20, verbose=True,
callbacks=[lgb.reset_parameter(learning_rate=lambda x: 0.95 ** x * 0.1)])

[1]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0
Training until validation scores don't improve for 20 rounds
[2]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.098694
[3]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.0782131
[4]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.0782131
[5]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.0782131
[6]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.333333
[7]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.333333
[8]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.333333
[9]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.333333
[10]	valid_0's ndcg@1: 0	valid_0's ndcg@3: 0.333333
[11]	valid_0's ndcg@1: 0.333333	valid_0's ndcg@3: 0.687148
[12]	valid_0's ndcg@1: 1	valid_0's ndcg@3: 0.843574
[13]	valid_0's ndcg@1: 1	valid_0's ndcg@3: 0.843574
[14]	valid_0's ndcg@1: 1	valid_0's ndcg@3: 0.843574
[15]	valid_0's ndcg@1: 1	valid_0's ndcg@3: 0.843574
[16]	valid_0's ndcg@1: 1	valid_0's ndcg@3: 0.843574
[17]	valid_0's ndcg@1: 0.333333	valid_0's ndcg@3: 0.530721
[18]	valid_0's ndcg@1: 0.333333	valid_0's ndcg@3: 0.53

LGBMRanker(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
           importance_type='split', learning_rate=0.1, max_depth=-1,
           min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
           n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
           random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
           subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [35]:
preds_train = gbm.predict(x_train)
preds_train

array([ 0.09126622, -0.90011971, -0.21296091, ..., -0.91282023,
       -1.04027268, -1.05699536])

In [36]:
spearmanr(y_train, preds_train)

SpearmanrResult(correlation=0.4481291965266587, pvalue=0.0)